# Generated by Django 3.0.6 on 2020-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='cycle',
            field=models.CharField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
