# Generated by Django 3.0.6 on 2020-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0003_auto_20200513_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='rate',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
