# Generated by Django 2.2.8 on 2020-04-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0003_savingcycle_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcycle',
            name='cycle_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='savingcycle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
