# Generated by Django 2.2.8 on 2020-04-18 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0003_customuser_application_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='application_fee',
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=123)),
                ('social_fund', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
