# Generated by Django 2.2.8 on 2020-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0004_auto_20200429_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcycle',
            name='archive_status',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('UNARCHIVED', 'UNARCHIVED')], max_length=200, null=True),
        ),
    ]
