# Generated by Django 3.0.6 on 2020-05-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0004_remove_saving_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='cycle',
        ),
    ]
