# Generated by Django 2.2.8 on 2020-05-02 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0005_savingcycle_archive_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('interest_rate', models.IntegerField(default=0)),
                ('loan_period', models.IntegerField(default=0)),
                ('recorded_by', models.CharField(blank=True, max_length=220, null=True)),
                ('cycle', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='savingsapp.SavingCycle')),
                ('name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
