# Generated by Django 2.2.8 on 2020-04-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0006_auto_20200418_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='attendance_month',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='attendance_year',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='social_fund',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=123, null=True)),
                ('social_fund', models.IntegerField(blank=True, default=1000, null=True)),
                ('attendance_year', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_month', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
