# Generated by Django 2.2.8 on 2020-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0006_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='cycle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
