# Generated by Django 3.0.6 on 2020-05-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0007_auto_20200514_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=30, null=True),
        ),
    ]
