# Generated by Django 2.2.8 on 2020-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0007_auto_20200502_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayingLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
    ]
