# Generated by Django 2.2.8 on 2020-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0008_auto_20200502_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingloan',
            name='loan_id',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
