# Generated by Django 2.2.8 on 2020-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0008_auto_20200418_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
