# Generated by Django 2.2.8 on 2020-05-02 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0009_payingloan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.ForeignKey(blank=True, default='kim', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
