# Generated by Django 2.2.8 on 2020-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0010_auto_20200502_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingloan',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
