# Generated by Django 2.2.8 on 2020-04-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0010_auto_20200419_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupsdetails',
            name='lookup_name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='savingsapp.LookUps'),
        ),
    ]
