# Generated by Django 3.0.6 on 2020-05-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0011_auto_20200514_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
