# Generated by Django 2.2.8 on 2020-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0011_lookupsdetails_lookup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_year',
            field=models.CharField(blank=True, default=2020, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lookups',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lookupsdetails',
            name='details',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
