# Generated by Django 2.2.8 on 2020-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0011_auto_20200502_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingloan',
            name='loan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
