# Generated by Django 2.2.8 on 2020-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0012_auto_20200420_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
