# Generated by Django 3.0.6 on 2020-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0012_attendance_attendance_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='social_fund',
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_fund',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
