# Generated by Django 3.0.5 on 2020-05-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0012_auto_20200502_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcycle',
            name='interest_rate',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
