# Generated by Django 3.0.6 on 2020-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0013_auto_20200515_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
