# Generated by Django 3.0.5 on 2020-05-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0013_savingcycle_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
