# Generated by Django 3.0.5 on 2020-05-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0014_auto_20200503_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_loanee',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
