# Generated by Django 2.2.8 on 2020-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0014_auto_20200422_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
