# Generated by Django 3.0.5 on 2020-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0015_loan_is_loanee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_loanee',
            field=models.BooleanField(default=True),
        ),
    ]
