# Generated by Django 2.2.8 on 2020-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0015_auto_20200422_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
