# Generated by Django 3.0.6 on 2020-05-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0015_auto_20200515_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialfund',
            old_name='amount',
            new_name='social_fund',
        ),
    ]
