# Generated by Django 2.2.8 on 2020-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0016_auto_20200422_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='social_fund',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
