# Generated by Django 2.2.8 on 2020-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0018_auto_20200423_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(default='1', max_length=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
