# Generated by Django 3.0.5 on 2020-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0018_lookup_lookupdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='name',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
