# Generated by Django 3.0.6 on 2020-05-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0019_remove_cycle_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingloan',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payingloan',
            name='total_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
