# Generated by Django 2.2.8 on 2020-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0019_auto_20200423_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
