# Generated by Django 3.0.6 on 2020-05-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0020_auto_20200517_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingloan',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('RUNNING', 'RUNNING'), ('SETTLED', 'SETTLED')], default='RUNNING', max_length=100, null=True),
        ),
    ]
