# Generated by Django 3.0.6 on 2020-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0021_payingloan_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingloan',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payingloan',
            name='total_paid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
