# Generated by Django 3.0.6 on 2020-05-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0023_auto_20200521_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telephone', models.IntegerField(blank=True, default=0, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('application_fee', models.IntegerField(blank=True, default=10000, null=True)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Ordinary', 'Ordinary')], max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Ordinary', 'Ordinary')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='sacco@gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='sacco', max_length=30, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='sacco', max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savingsapp.Member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='savingsapp.Member'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='savingsapp.Member'),
        ),
    ]
