# Generated by Django 2.2.8 on 2020-09-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0025_member_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Ordinary', 'Ordinary')], default='Admin', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='Name', max_length=100, null=True),
        ),
    ]
